config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :test_og_previewers
  resources :og_previewers, only: %i[index show new create destroy] do
    get 'progress' => 'og_previewers#progress'
  end

  root to: 'og_previewers#new'
end

app/models/application_record.rb
# frozen_string_literal: true

# Base for our models
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/og_previewer.rb
# frozen_string_literal: true

class OgPreviewer < ApplicationRecord
  validates :input_url, presence: true, format: URI.regexp(%w[http https])
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/og_previewers_controller.rb
# frozen_string_literal: true

# This page will handle creation and display for the user's inputted url
# and associated data (as well as enqueing jobs to process
# that url) and another input to poll the status of enqueued jobs
class OgPreviewersController < ApplicationController
  before_action :set_og_previewer, only: %i[show update destroy]

  # GET /og_previewers
  # GET /og_previewers.json
  def index
    @og_previewers = OgPreviewer.all
  end

  # GET /og_previewers/1
  # GET /og_previewers/1.json
  def show; end

  # GET /og_previewers/new
  def new
    @og_previewer = OgPreviewer.new
  end

  def create
    @og_previewer = OgPreviewer.new(og_previewer_params)
    respond_to do |format|
      if @og_previewer.save
        @current_job = FetchOgDataJob.perform_later(@og_previewer)
        @og_previewer.update(job_id: @current_job.job_id)
      end
      format.js
    end
  end

  # DELETE /og_previewers/1
  # DELETE /og_previewers/1.json
  def destroy
    @og_previewer.destroy
    respond_to do |format|
      format.html do
        redirect_to og_previewers_url,
                    notice: 'Og previewer was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  # Receive the polling to check status of the job
  # when it is complete, render a partial to display resulting image
  def progress
    # fetch job status
    status = ActiveJob::Status.get(params[:job_id])
    if status.completed?
      # Only hit the DB if job is completed for efficiency
      @og_previewer = OgPreviewer.find(params[:og_previewer_id])
      render partial: 'og_image', locals: { og_previewer: @og_previewer }
    else
      render html: 'Still Processing...'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_og_previewer
    @og_previewer = OgPreviewer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def og_previewer_params
    params.require(:og_previewer).permit(:input_url, :og_image_url, :job_id, :status)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DanOgPreviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/og_previewers/_form.html.erb
<%= form_with(model: og_previewer, remote: true, class: 'input-url-form') do |form| %>
  <div id="error_explanation">
  </div>
  <div class="field">
    <%= form.text_field :input_url, :placeholder => 'Enter a URL here...' %>
  </div>

  <div class="actions">
    <%= form.submit 'Process URL' %>
  </div>
<% end %>
<div id='og_output'>
</div>

app/views/og_previewers/_og_image.html.erb
<% if og_previewer.present?  %>
  <div class='og_image_container'>
    <% if og_previewer.status == 'completed' %>
      <% if og_previewer.og_image_url.present? %>
        <img src="<%= og_previewer.og_image_url %>">
      <% else %>
          <h3>No image retrieved</h3>
      <% end %>
    <% else %>
      <h3>Processing...</h3>
    <% end %>
  </div>
<% end %>

app/views/og_previewers/create.js.erb
<% if @og_previewer.errors.any? %>
    // This removes any error messages that were previously generated
    $('#error_explanation').empty();
    $('#og_output').empty();
    $('#error_explanation').show();
    $('#error_explanation').append("<h2><%= pluralize(@og_previewer.errors.count, "error") %> prohibited this from being processed:</h2>");
    $('#error_explanation').append('<ul>');
    <% @og_previewer.errors.full_messages.each do |message| %>
      $('#error_explanation').append("<li><%= message %></li>");
    <% end %>
    $('#error_explanation').append('</ul>');
<% else %>
    $('#error_explanation').empty();
    $('#error_explanation').hide();
    $('#og_output').html('Processing...');
    // Start polling for when job completes
    $(document).ready(function() {
      $(function() {
        setTimeout(getProgress, 250);
      });
      function getProgress() {
        $.ajax({
          url: "<%= og_previewer_progress_path(og_previewer_id: @og_previewer.id, job_id: @og_previewer.job_id) %>",
          method: 'GET',
          dataType: 'html',                   
          success: function(result) {
            $('#og_output').html(result);
            if (result == 'Still Processing...') {
              setTimeout(getProgress, 1000);
            }
          }
        });
      }
    });

<% end %>

app/views/og_previewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Og Previewers</h1>

<table>
  <thead>
    <tr>
      <th>Input url</th>
      <th>Og image url</th>
      <th>Job</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @og_previewers.each do |og_previewer| %>
      <tr>
        <td><%= og_previewer.input_url %></td>
        <td><%= og_previewer.og_image_url %></td>
        <td><%= og_previewer.job_id %></td>
        <td><%= og_previewer.status %></td>
        <td><%= link_to 'Show', og_previewer %></td>
        <td><%= link_to 'Destroy', og_previewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Og Previewer', new_og_previewer_path %>

app/views/og_previewers/new.html.erb
<h1>Preview a URL</h1>
<%= render 'form', og_previewer: @og_previewer %>
<%= link_to 'Back', og_previewers_path %>

app/views/og_previewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input url:</strong>
  <%= @og_previewer.input_url %>
</p>
<p>
  <strong>Status:</strong>
  <%= @og_previewer.status %>
</p>
<p>
  <strong>Job ID:</strong>
  <%= @og_previewer.job_id %>
</p>
<p>
  <strong>Og image url:</strong>
  <%= @og_previewer.og_image_url %>
</p>

<% render partial: 'og_previewers/og_image', locals: {og_previewer: @og_previewer} %>


<%= link_to 'Back', og_previewers_path %>